### ISSUE TITLE
Use a web bundler

### ISSUE THREAD

**Issue by shahoob** [Ascript89/onliine#1]
It isn't necessary but using one not only can possible bring down loading times a bit but also make your life WAY easier.

how about you try with [Vite](https://vitejs.dev/)? it's also very fast in development and still fast in production

**Comment by shahoob** [comment]
if you want i can also try to migrate your code to vite too

**Comment by jerosajose** [comment]
I'm open for any types of collaboration! This meaning you can of course try migrating it and making a request to the repository.
Regarding the previous idea, I'll surely need some sort of framework or tool to bundle the site, as pure HTML/CSS won't be enough to build what's planned on the next big update for the site.

You can find more info in the Discord server about the overhaul, but it mainly consists in linking your Steam account so that your games appear as channels in the menu, and the idea of making it the default "New Tab" page with customizable bookmarks (the channels).

Thanks for the note and the suggestion, I'll keep it in mind!
